[package]
name = "PA-BOTNET-CLIENT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
regex = "1.4"
cpal = "0.15.2"
rodio = "0.17.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.80"
arc = "0.0.1"
mutex = "0.1.0"
nmap = "0.1.3"